In [ ]:
import yfinance as yf
meta = yf.Ticker("META")
data = meta.history(period = "max")
data.to_string()

ModuleNotFoundError: No module named 'yfinance'

In [2]:
import datetime
import yfinance as yf
start_date = datetime.datetime(2019, 5, 31)
end_date = datetime.datetime.now()
meta = yf.Ticker("META")
data = meta.history(start= start_date, end = end_date)
print(data.to_string())

                                 Open        High         Low       Close     Volume  Dividends  Stock Splits
Date
2019-05-31 00:00:00-04:00  178.710631  178.968362  175.617796  175.925095   15226500      0.000           0.0
2019-06-03 00:00:00-04:00  173.476626  173.526194  159.608404  162.721069   56059600      0.000           0.0
2019-06-04 00:00:00-04:00  162.284885  166.815094  159.439858  166.041885   46044300      0.000           0.0
2019-06-05 00:00:00-04:00  166.022044  167.251255  163.196863  166.706039   19758300      0.000           0.0
2019-06-06 00:00:00-04:00  166.834917  168.222724  165.774224  166.864655   12446400      0.000           0.0
2019-06-07 00:00:00-04:00  168.688647  172.356435  167.370223  171.840973   16917300      0.000           0.0
2019-06-10 00:00:00-04:00  173.228789  176.311717  172.287062  173.298187   14767900      0.000           0.0
2019-06-11 00:00:00-04:00  176.926303  178.413246  175.251013  176.549622   15266600      0.000           0.0
2019-06-12 00:00:00-04:00  176.827203  177.709455  171.375080  173.516266   17699800      0.000           0.0
2019-06-13 00:00:00-04:00  174.001980  176.480217  173.089991  175.925095   12253600      0.000           0.0
2019-06-14 00:00:00-04:00  178.938642  180.257066  178.433087  179.751511   16773700      0.000           0.0
2019-06-17 00:00:00-04:00  183.399460  187.850379  182.804692  187.364639   29459900      0.000           0.0
2019-06-18 00:00:00-04:00  192.311174  192.836559  185.649672  186.829315   37571400      0.000           0.0
2019-06-19 00:00:00-04:00  185.372159  186.462590  182.943490  185.847977   21417100      0.000           0.0
2019-06-20 00:00:00-04:00  189.287764  189.495943  186.006580  187.880127   14635700      0.000           0.0
2019-06-21 00:00:00-04:00  187.106895  190.328604  187.106895  189.476089   22751200      0.000           0.0
2019-06-24 00:00:00-04:00  190.744929  192.291347  189.902338  190.923370   15509000      0.000           0.0
2019-06-25 00:00:00-04:00  191.200961  191.458692  186.492310  187.196121   16750300      0.000           0.0
2019-06-26 00:00:00-04:00  187.890022  189.099403  185.679438  186.026398   12808600      0.000           0.0
2019-06-27 00:00:00-04:00  188.227069  197.148723  186.631084  187.850372   11159000      0.000           0.0
2019-06-28 00:00:00-04:00  188.891246  191.518172  188.286556  191.319916   16378900      0.000           0.0
2019-07-01 00:00:00-04:00  193.510684  193.580067  190.259223  191.319916   14181800      0.000           0.0
2019-07-02 00:00:00-04:00  191.319931  193.302521  191.032462  193.302521    9050000      0.000           0.0
2019-07-03 00:00:00-04:00  192.469808  195.681593  192.469808  195.483337   10246100      0.000           0.0
2019-07-05 00:00:00-04:00  194.472222  195.354488  192.479724  194.690308   11164100      0.000           0.0
2019-07-08 00:00:00-04:00  193.490847  194.967867  191.954337  194.055878    9723900      0.000           0.0
2019-07-09 00:00:00-04:00  193.272765  197.723684  193.193459  197.475861   14698600      0.000           0.0
2019-07-10 00:00:00-04:00  198.258979  201.193219  197.931850  200.965210   20571700      0.000           0.0
2019-07-11 00:00:00-04:00  201.490614  202.025922  198.467177  199.478287   13678500      0.000           0.0
2019-07-12 00:00:00-04:00  197.941785  203.512874  197.426323  203.086609   15366300      0.000           0.0
2019-07-15 00:00:00-04:00  202.471955  203.542555  200.063116  202.134918   16030300      0.000           0.0
2019-07-16 00:00:00-04:00  202.115104  203.681352  201.331988  202.065536   12132700      0.000           0.0
2019-07-17 00:00:00-04:00  202.402591  202.581032  199.835141  200.043320   12083700      0.000           0.0
2019-07-18 00:00:00-04:00  198.407675  200.707487  197.644389  199.032196   11937900      0.000           0.0
2019-07-19 00:00:00-04:00  200.419978  200.568681  196.345771  196.633240   12098300      0.000           0.0
2019-07-22 00:00:00-04:00  198.169783  200.806631  197.079352  200.558807   13589000      0.000           0.0
2019-07-23 00:00:00-04:00  201.074252  202.462074  199.210628  200.598434   14583700      0.000           0.0
2019-07-24 00:00:00-04:00  195.909587  203.027076  195.503152  202.878387   32532500      0.000           0.0
2019-07-25 00:00:00-04:00  204.900661  206.843606  196.534130  198.962814   39889900      0.000           0.0
2019-07-26 00:00:00-04:00  198.447326  201.113912  194.541622  198.011154   24434000      0.000           0.0
2019-07-29 00:00:00-04:00  197.267689  197.892210  193.599901  194.234329   16530800      0.000           0.0
2019-07-30 00:00:00-04:00  193.689092  196.980198  191.815545  195.324722   11903600      0.000           0.0
2019-07-31 00:00:00-04:00  195.235508  197.029749  191.002675  192.539185   14593500      0.000           0.0
2019-08-01 00:00:00-04:00  192.479728  196.742300  189.218375  191.052261   17777000      0.000           0.0
2019-08-02 00:00:00-04:00  189.436437  190.943194  186.432815  187.374542   15297000      0.000           0.0
2019-08-05 00:00:00-04:00  183.082250  184.053714  177.778816  180.148010   23086700      0.000           0.0
2019-08-06 00:00:00-04:00  182.090955  184.172665  181.496172  182.903809   18035700      0.000           0.0
2019-08-07 00:00:00-04:00  182.001728  184.747604  179.642442  183.538223   15833200      0.000           0.0
2019-08-08 00:00:00-04:00  184.995461  188.683080  182.447841  188.504654   14828900      0.000           0.0
2019-08-09 00:00:00-04:00  188.346030  189.317495  185.491096  186.214752   11058800      0.000           0.0
2019-08-12 00:00:00-04:00  185.223444  185.956993  182.854250  183.756317   10930900      0.000           0.0
2019-08-13 00:00:00-04:00  183.905008  189.713996  183.756304  186.809494   13577000      0.000           0.0
2019-08-14 00:00:00-04:00  184.182581  184.370930  177.749072  178.145599   18903700      0.000           0.0
2019-08-15 00:00:00-04:00  179.374826  181.605240  178.462837  181.000549   12925900      0.000           0.0
2019-08-16 00:00:00-04:00  182.150444  183.488698  180.772544  182.100876   12654600      0.000           0.0
2019-08-19 00:00:00-04:00  184.390767  185.867802  183.240876  184.549377    9691200      0.000           0.0
2019-08-20 00:00:00-04:00  183.835623  184.380838  180.802263  182.209900   10083400      0.000           0.0
2019-08-21 00:00:00-04:00  183.389554  184.281713  181.545744  181.952179    8398200      0.000           0.0
2019-08-22 00:00:00-04:00  181.833206  182.507295  178.343859  180.455307   10821400      0.000           0.0
2019-08-23 00:00:00-04:00  179.265765  181.535839  175.122159  176.202667   17323400      0.000           0.0
2019-08-26 00:00:00-04:00  177.838283  178.928713  176.688392  178.789932    8773600      0.000           0.0
2019-08-27 00:00:00-04:00  180.346261  182.437894  179.434272  179.721756   14399600      0.000           0.0
2019-08-28 00:00:00-04:00  178.958476  180.366113  177.362491  180.177765    9386100      0.000           0.0
2019-08-29 00:00:00-04:00  182.170286  184.460175  181.872895  183.954620   10128700      0.000           0.0
2019-08-30 00:00:00-04:00  185.154033  185.173864  181.862943  184.053696   10774500      0.000           0.0
2019-09-03 00:00:00-04:00  182.398262  184.053723  180.524715  180.802277    9779400      0.000           0.0
2019-09-04 00:00:00-04:00  183.042581  186.115600  182.289202  185.510910   11308000      0.000           0.0
2019-09-05 00:00:00-04:00  186.888841  189.694207  186.303980  189.238205   13876700      0.000           0.0
2019-09-06 00:00:00-04:00  188.554172  188.554172  184.727774  185.857849   15226800      0.000           0.0
2019-09-09 00:00:00-04:00  186.095789  187.334907  184.232165  187.116821   14722400      0.000           0.0
2019-09-10 00:00:00-04:00  185.808326  186.462585  182.943484  184.549377   15455900      0.000           0.0
2019-09-11 00:00:00-04:00  184.836855  187.790909  184.460158  186.849182   11761700      0.000           0.0
2019-09-12 00:00:00-04:00  188.207206  189.267884  185.600097  185.838013   11419800      0.000           0.0
2019-09-13 00:00:00-04:00  185.699282  186.333710  184.916150  185.560501   11441100      0.000           0.0
2019-09-16 00:00:00-04:00  185.302749  186.155263  184.152858  184.598938    8444800      0.000           0.0
2019-09-17 00:00:00-04:00  185.035127  186.680681  183.924867  186.442764    9671100      0.000           0.0
2019-09-18 00:00:00-04:00  186.452660  187.434047  184.390765  186.502228    9681900      0.000           0.0
2019-09-19 00:00:00-04:00  187.017720  189.436483  186.512150  188.484833   10392700      0.000           0.0
2019-09-20 00:00:00-04:00  189.000283  191.419045  186.482385  188.276627   19934200      0.000           0.0
2019-09-23 00:00:00-04:00  187.691778  188.445172  183.597740  185.193726   13327600      0.000           0.0
2019-09-24 00:00:00-04:00  186.343607  186.403083  178.819683  179.701935   18546600      0.000           0.0
2019-09-25 00:00:00-04:00  179.870456  181.823308  176.321618  181.208710   18068300      0.000           0.0
2019-09-26 00:00:00-04:00  179.751511  179.820893  176.123367  178.542130   16083300      0.000           0.0
2019-09-27 00:00:00-04:00  178.918808  179.186447  174.130852  175.558319   14656200      0.000           0.0
2019-09-30 00:00:00-04:00  176.321591  177.114630  175.310482  176.529770   10740000      0.000           0.0
2019-10-01 00:00:00-04:00  177.590462  178.274458  173.357644  174.279541   17073000      0.000           0.0
2019-10-02 00:00:00-04:00  173.317994  174.993285  171.583228  173.080093   16151700      0.000           0.0
2019-10-03 00:00:00-04:00  174.041650  178.274469  172.118536  177.818481   16086300      0.000           0.0
2019-10-04 00:00:00-04:00  177.987021  179.404566  176.549647  178.879181   10430200      0.000           0.0
2019-10-07 00:00:00-04:00  178.433082  179.602802  176.539705  178.115860    9178300      0.000           0.0
2019-10-08 00:00:00-04:00  176.708222  178.799855  176.172930  176.202667    9466900      0.000           0.0
2019-10-09 00:00:00-04:00  177.600397  179.146815  176.391016  178.284393    7556900      0.000           0.0
2019-10-10 00:00:00-04:00  178.750314  180.029077  177.610315  178.462830    8605000      0.000           0.0
2019-10-11 00:00:00-04:00  180.564344  184.866575  180.554436  182.586594   14930500      0.000           0.0
2019-10-14 00:00:00-04:00  182.596514  183.012856  180.980714  181.684525    7006000      0.000           0.0
2019-10-15 00:00:00-04:00  182.199995  188.722717  182.061214  187.245682   15039100      0.000           0.0
2019-10-16 00:00:00-04:00  186.680644  188.048621  185.272993  187.899933   10516900      0.000           0.0
2019-10-17 00:00:00-04:00  188.643423  189.178715  187.126743  188.732635    9603000      0.000           0.0
2019-10-18 00:00:00-04:00  188.574055  189.823097  182.318986  184.232193   16874200      0.000           0.0
2019-10-21 00:00:00-04:00  185.411785  188.256812  185.124316  188.108109    8122600      0.000           0.0
2019-10-22 00:00:00-04:00  188.346039  188.990375  179.920032  180.752716   19537600      0.000           0.0
2019-10-23 00:00:00-04:00  180.425566  184.757534  180.415658  184.529526   12300400      0.000           0.0
2019-10-24 00:00:00-04:00  183.012834  185.104467  181.208686  184.757523   11413500      0.000           0.0
2019-10-25 00:00:00-04:00  184.212329  187.354732  183.478766  186.254395    8061200      0.000           0.0
2019-10-28 00:00:00-04:00  185.570421  187.880140  183.468880  187.751266   13657900      0.000           0.0
2019-10-29 00:00:00-04:00  190.021320  190.854004  186.829349  187.662033   13574900      0.000           0.0
2019-10-30 00:00:00-04:00  187.909846  188.792097  184.361008  186.611252   28734600      0.000           0.0
2019-10-31 00:00:00-04:00  194.987717  196.365616  186.611277  189.981674   42286500      0.000           0.0
2019-11-01 00:00:00-04:00  191.171223  192.420249  188.256814  191.934509   21711800      0.000           0.0
2019-11-04 00:00:00-05:00  192.856430  195.651874  192.122866  193.024948   16371300      0.000           0.0
2019-11-05 00:00:00-05:00  193.669281  194.045978  191.914700  192.628433    9942000      0.000           0.0
2019-11-06 00:00:00-05:00  192.340960  192.677997  189.684297  189.882553   10973000      0.000           0.0
2019-11-07 00:00:00-05:00  190.239410  191.756090  187.820648  188.762375   13473000      0.000           0.0
2019-11-08 00:00:00-05:00  188.346012  190.665638  188.048620  189.178696   10760800      0.000           0.0
2019-11-11 00:00:00-05:00  188.276603  188.425306  186.898704  187.959396    8631200      0.000           0.0
2019-11-12 00:00:00-05:00  188.345996  193.361945  188.088265  192.777084   17615500      0.000           0.0
2019-11-13 00:00:00-05:00  193.005105  193.996400  191.062175  191.508255   10860700      0.000           0.0
2019-11-14 00:00:00-05:00  191.250527  192.340957  189.783414  191.468613    9040500      0.000           0.0
2019-11-15 00:00:00-05:00  192.568958  193.599913  191.696629  193.401657   11524300      0.000           0.0
2019-11-18 00:00:00-05:00  192.866321  196.900898  191.369471  195.681595   16167200      0.000           0.0
2019-11-19 00:00:00-05:00  195.681600  198.258973  195.146308  197.584900   19056800      0.000           0.0
2019-11-20 00:00:00-05:00  196.851312  197.852514  193.728724  195.790619   12355400      0.000           0.0
2019-11-21 00:00:00-05:00  195.701431  197.356891  195.146308  196.206985   12131000      0.000           0.0
2019-11-22 00:00:00-05:00  196.653092  197.565081  195.899698  197.089264    9959800      0.000           0.0
2019-11-25 00:00:00-05:00  197.783173  199.220548  197.515519  198.050812   15272300      0.000           0.0
2019-11-26 00:00:00-05:00  198.258978  198.407666  196.316033  197.237946   11735500      0.000           0.0
2019-11-27 00:00:00-05:00  198.159867  201.371668  197.684049  200.241592   12736600      0.000           0.0
2019-11-29 00:00:00-05:00  199.845059  202.025905  199.458455  199.884705    7985200      0.000           0.0
2019-12-02 00:00:00-05:00  200.370417  200.419970  196.325933  197.961563   11503400      0.000           0.0
2019-12-03 00:00:00-05:00  195.879883  197.198292  193.381815  197.089264   11595300      0.000           0.0
2019-12-04 00:00:00-05:00  198.258988  198.288726  196.325966  196.980225    8456300      0.000           0.0
2019-12-05 00:00:00-05:00  198.120190  199.537734  196.484559  197.624542    9740400      0.000           0.0
2019-12-06 00:00:00-05:00  198.754620  199.815313  198.318448  199.299835   12270600      0.000           0.0
2019-12-09 00:00:00-05:00  198.903300  201.371629  198.467143  199.587296   11954800      0.000           0.0
2019-12-10 00:00:00-05:00  199.904546  200.291150  198.407681  199.121414    9475700      0.000           0.0
2019-12-11 00:00:00-05:00  198.536569  200.866118  198.536569  200.499329    8036800      0.000           0.0
2019-12-12 00:00:00-05:00  200.588551  201.887145  192.410367  195.037292   23734800      0.000           0.0
2019-12-13 00:00:00-05:00  194.690285  195.086812  191.488408  192.420227   18798000      0.000           0.0
2019-12-16 00:00:00-05:00  193.570142  197.386618  193.114140  196.197067   14911500      0.000           0.0
2019-12-17 00:00:00-05:00  197.109074  197.267685  194.422673  196.662994   10175700      0.000           0.0
2019-12-18 00:00:00-05:00  198.348189  202.521547  198.348189  200.737213   23274400      0.000           0.0
2019-12-19 00:00:00-05:00  201.014759  204.504121  200.747105  204.266205   16514600      0.000           0.0
2019-12-20 00:00:00-05:00  205.673871  205.901880  201.659124  204.504150   27306900      0.000           0.0
2019-12-23 00:00:00-05:00  204.900640  206.774187  203.889515  204.385162   13348900      0.000           0.0
2019-12-24 00:00:00-05:00  204.504148  204.989872  203.215461  203.334412    6046300      0.000           0.0
2019-12-26 00:00:00-05:00  203.780495  206.010908  203.522748  205.981155    9350700      0.000           0.0
2019-12-27 00:00:00-05:00  206.853513  207.111244  204.791618  206.288483   10284200      0.000           0.0
2019-12-30 00:00:00-05:00  206.050549  206.090194  202.125015  202.630585   10524300      0.000           0.0
2019-12-31 00:00:00-05:00  202.224138  203.770556  201.827626  203.463257    8953500      0.000           0.0
2020-01-02 00:00:00-05:00  204.950235  207.963765  204.474418  207.953857   12077100      0.000           0.0
2020-01-03 00:00:00-05:00  205.406218  208.568436  205.148472  206.853500   11188400      0.000           0.0
2020-01-06 00:00:00-05:00  204.900649  210.927724  204.722223  210.749298   17058900      0.000           0.0
2020-01-07 00:00:00-05:00  210.967360  212.712034  209.906668  211.205261   14912400      0.000           0.0
2020-01-08 00:00:00-05:00  211.145806  214.357606  210.759201  213.346481   13475000      0.000           0.0
2020-01-09 00:00:00-05:00  215.646264  216.478964  214.397238  216.399658   12642800      0.000           0.0
2020-01-10 00:00:00-05:00  217.291834  217.965922  215.527330  216.161758   12119400      0.000           0.0
2020-01-13 00:00:00-05:00  217.688352  220.037716  217.301748  219.978241   14463400      0.000           0.0
2020-01-14 00:00:00-05:00  219.680866  220.444167  216.726811  217.153061   13288900      0.000           0.0
2020-01-15 00:00:00-05:00  218.689561  219.750239  218.223651  219.224854   10036500      0.000           0.0
2020-01-16 00:00:00-05:00  220.632516  220.691992  218.471486  219.839478   10015300      0.000           0.0
2020-01-17 00:00:00-05:00  220.097180  220.354911  218.610237  220.206223   15905900      0.000           0.0
2020-01-21 00:00:00-05:00  220.226078  220.434241  217.212533  219.512344   14275800      0.000           0.0
2020-01-22 00:00:00-05:00  220.374744  220.810916  219.353711  219.393372   12212800      0.000           0.0
2020-01-23 00:00:00-05:00  218.828342  219.561905  217.361230  217.846954   11195000      0.000           0.0
2020-01-24 00:00:00-05:00  218.877905  219.849369  214.228730  216.042801   11905800      0.000           0.0
2020-01-27 00:00:00-05:00  211.244946  214.179170  210.650163  212.999527   13810700      0.000           0.0
2020-01-28 00:00:00-05:00  214.258474  216.835846  211.661286  215.894104   13413800      0.000           0.0
2020-01-29 00:00:00-05:00  219.512332  222.248300  216.548355  221.286743   33181300      0.000           0.0
2020-01-30 00:00:00-05:00  204.732124  209.589463  202.967621  207.706009   48775500      0.000           0.0
2020-01-31 00:00:00-05:00  206.615559  206.873306  199.309722  200.152328   31359900      0.000           0.0
2020-02-03 00:00:00-05:00  201.669050  203.354249  200.737230  202.412521   15495600      0.000           0.0
2020-02-04 00:00:00-05:00  204.821355  208.766719  203.413718  208.003418   19628900      0.000           0.0
2020-02-05 00:00:00-05:00  210.660046  210.878132  206.893138  208.280945   12538200      0.000           0.0
2020-02-06 00:00:00-05:00  208.637829  209.351563  207.517661  209.014526   10567500      0.000           0.0
2020-02-07 00:00:00-05:00  208.469331  210.967399  208.102542  210.481659   12242500      0.000           0.0
2020-02-10 00:00:00-05:00  209.678674  211.938825  208.826160  211.205261   11856400      0.000           0.0
2020-02-11 00:00:00-05:00  208.360268  209.024433  204.712295  205.386383   25030800      0.000           0.0
2020-02-12 00:00:00-05:00  206.040637  209.381295  205.594542  208.925293   13813700      0.000           0.0
2020-02-13 00:00:00-05:00  207.696094  212.464220  207.359042  211.284576   15396600      0.000           0.0
2020-02-14 00:00:00-05:00  212.137111  213.059008  210.798856  212.315536   10741700      0.000           0.0

In [4]:
data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-05-31 00:00:00-04:00,178.710631,178.968362,175.617796,175.925095,15226500,0.0,0.0
2019-06-03 00:00:00-04:00,173.476626,173.526194,159.608404,162.721069,56059600,0.0,0.0
2019-06-04 00:00:00-04:00,162.284885,166.815094,159.439858,166.041885,46044300,0.0,0.0
2019-06-05 00:00:00-04:00,166.022044,167.251255,163.196863,166.706039,19758300,0.0,0.0
2019-06-06 00:00:00-04:00,166.834917,168.222724,165.774224,166.864655,12446400,0.0,0.0
...,...,...,...,...,...,...,...
2026-06-26 00:00:00-04:00,543.340027,556.849976,540.400024,550.250000,18867700,0.0,0.0
2026-06-29 00:00:00-04:00,560.000000,570.900024,558.000000,562.599976,15011400,0.0,0.0
2026-06-30 00:00:00-04:00,560.940002,565.539978,551.429993,563.289978,18111100,0.0,0.0
2026-07-01 00:00:00-04:00,607.909973,628.280029,595.099976,612.909973,45536300,0.0,0.0
2026-07-02 00:00:00-04:00,607.900024,610.000000,580.419983,582.900024,21705900,0.0,0.0

In [5]:
import pandas as pd

In [6]:
path = r"E:\Download\Stock_Data_List.xlsx"

In [7]:
df = pd.read_excel(path)

In [8]:
all_stock_symbol = df['Stock Symbol'].values

In [9]:
all_stock_symbol

array(['TCS.NS', 'WIPRO.NS', 'INFY.NS', 'SBIN.NS', 'HDFCBANK.NS',
       'BANKBARODA.NS', 'ICICIBANK.NS', 'AXISBANK.NS', 'TMCV.BO',
       'MARUTI.NS', 'HEROMOTOCO.NS', 'HONDAPOWER.NS', 'RELIANCE.NS'],
      dtype=object)

In [10]:
import datetime
import yfinance as yf

all_stock_symbol = ['TCS.NS',      'WIPRO.NS',       'INFY.NS',       'SBIN.NS',
   'HDFCBANK.NS', 'BANKBARODA.NS',  'ICICIBANK.NS',   'AXISBANK.NS',
 'TMCV.BO', 'MARUTI.NS', 'HEROMOTOCO.NS', 'HONDAPOWER.NS',
   'RELIANCE.NS']

empty_df = pd.DataFrame()

for i in all_stock_symbol:
    start_date = datetime.datetime(2015, 1, 1)
    end_date = datetime.datetime.now()
    meta = yf.Ticker(i)
    data = meta.history(start= start_date, end = end_date)
    data['Company_Name'] = i
    empty_df = pd.concat([empty_df,data])
print('Done')

Done

In [11]:
stock_df = empty_df.reset_index()

In [12]:
stock_df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Company_Name
0,2015-01-01 00:00:00+05:30,983.872460,983.872460,973.907254,975.651184,366830,0.0,0.0,TCS.NS
1,2015-01-02 00:00:00+05:30,977.739527,993.051423,977.586254,988.643738,925740,0.0,0.0,TCS.NS
2,2015-01-05 00:00:00+05:30,989.237798,996.481695,967.640105,973.619263,1754242,0.0,0.0,TCS.NS
3,2015-01-06 00:00:00+05:30,969.346255,969.346255,935.196225,937.725891,2423784,0.0,0.0,TCS.NS
4,2015-01-07 00:00:00+05:30,946.694085,950.201032,922.720093,926.648682,2636332,0.0,0.0,TCS.NS
...,...,...,...,...,...,...,...,...,...
34269,2026-06-30 00:00:00+05:30,1306.900024,1306.900024,1290.000000,1293.900024,15695263,0.0,0.0,RELIANCE.NS
34270,2026-07-01 00:00:00+05:30,1298.900024,1312.199951,1296.500000,1308.000000,7001401,0.0,0.0,RELIANCE.NS
34271,2026-07-02 00:00:00+05:30,1310.000000,1313.199951,1299.000000,1303.500000,17795024,0.0,0.0,RELIANCE.NS
34272,2026-07-03 00:00:00+05:30,1312.000000,1312.000000,1302.000000,1304.000000,7839550,0.0,0.0,RELIANCE.NS
34273,2026-07-06 00:00:00+05:30,1304.000000,1325.599976,1299.400024,1321.900024,7286667,0.0,0.0,RELIANCE.NS

In [13]:
import datetime
import yfinance as yf

all_stock_symbol = ['TCS.NS',      'WIPRO.NS',       'INFY.NS',       'SBIN.NS',
   'HDFCBANK.NS', 'BANKBARODA.NS',  'ICICIBANK.NS',   'AXISBANK.NS',
 'TMCV.BO',     'MARUTI.NS', 'HEROMOTOCO.NS', 'HONDAPOWER.NS',
   'RELIANCE.NS']

empty_df = pd.DataFrame()

for i in all_stock_symbol:
    start_date = datetime.datetime(2015, 1, 1)
    end_date = datetime.datetime.now()
    meta = yf.Ticker(i)
    data = meta.history(start= start_date, end = end_date)
    data['Company_Name'] = i
    empty_df = pd.concat([empty_df,data])

stock_df = empty_df.copy()